### ISSUE TITLE
[BUG] SUB CLUB BUGGY

### ISSUE THREAD

**Issue by quincyentertainment** [dlxmedia/community#25]
### 🦄 Select your Profile

- [ ] Streamer
- [ ] User

### ⚙️ Device

- [ ] Phone
- [ ] Computer

### 💾 System

None

### 🖥️ Browser

None

### 📍 Where is the Bug?

None

### ℹ️ Description

Varies of different reports from different sub club members.
majority of them do not see the sub club content, its all blurred out and when they click the content it brings them to subscription page even though they are.

some members sub club badges do not show up ( this also is happening to moderators, they are mods but the mod badge is gone along with there mod settings even though i checked on the dashboard and they are still an active mod) 

sometimes new content shows up with just an error page.

### 🧨 How to reproduce

.

### 😇 Anything else you could add?

Here some the usernames that have this issue that I can remember from the top of my head.

Sirz
MrKindaNiceGuy

**Comment by ecilion** [comment]
Investigating

**Comment by ecilion** [comment]
Hi @quincyentertainment, we fixed some errors we had with sub clubs last week, especially for the badges when the user is `moderator + subscriber` (they have to logout and login again for it to properly work).
I checked the 2 users you put in the comment and they are working fine. For them the issue seems to be solved.
If other users have the same issue, you can tell them to contact the Customer Support or send us their usernames if you prefer.

**Comment by ecilion** [comment]
> hello, the subclub member Sirz still has the same problem.

Going to take a look at it. Thanks for reporting it.

**Comment by quincyentertainment** [comment]
Hey! Hope all is well,
I'm sorry to that that they still have the same issue.

**Comment by ecilion** [comment]
> Hey! Hope all is well, I'm sorry to that that they still have the same issue.

Hi @quincyentertainment,
it seems our fix didn't work for those users.
We tested it with other users and it worked well for them.
Our customer support is going to reach out to them (`Sirz` and `MrKindaNiceGuy`) to try and solve the issue.
Thanks again for your time.

**Comment by Korrieanne** [comment]
Hi @quincyentertainment We have reached out via email but have not received a response. We will email them again, but if you can let them know we are trying to reach them. So Sorry for the inconvenience!

**Comment by quincyentertainment** [comment]
Hello, So I have another member with the same issue

Quentin250 

he sent me a video to show he cant access subclub content.






https://user-images.githubusercontent.com/125763737/227393604-b75353cf-9ab4-4105-a6ab-1406018b2f88.mp4
